Login Interface (Frontend part)
lauralindal/dein-semesterplaner pull request #50
Opened 2016-11-28 09:55 UTC by lauralindal

solves #41 as well as #44 
- Header now has a Login Component
- Cleaned up rendering in index.html
- included simple Login interface (no functionality yet)

Please review @noobiba @schultyy

2016-11-28 13:29 UTC, noobiba commented on src/Login.js
> +          <label htmlFor="exampleEmailInput">&nbsp;</label>
There is an email field which is actually not visible.

2016-11-28 13:31 UTC, noobiba reviewed
@lauralindal Please take a look at "<label htmlFor="exampleEmailInput">&nbsp;</label>". Seems that this will not be displayed. Is this your intention?

2016-11-28 13:32 UTC, noobiba reviewed
@lauralindal Please take a look at my comment in src/Login.js. thank you.

2016-11-28 22:19 UTC, schultyy commented on src/Login.js
> +          <label htmlFor="exampleEmailInput">&nbsp;</label>
I think the email field is missing, no?

2016-11-28 22:23 UTC, schultyy requested changes
As Tanja already commented, the email field is missing.

2016-11-30 18:58 UTC, schultyy approved these changes
![lgtm](http://i.giphy.com/u23zXEvNsIbfO.gif)

2016-11-30 18:59 UTC, merged

2016-12-01 12:27 UTC, noobiba commented on src/Login.js
> +          <label htmlFor="Username">Password</label>
<label htmlFor="Username">Password</label>
should be
<label htmlFor="Password">Password</label>

2016-12-01 12:32 UTC, noobiba commented on src/Login.js
> +        <div className="three columns">
Where is the username field gone..?
 ```
<label htmlFor="Username">User name</label>
 +          
<input type="username" placeholder="Username" />
```

2016-12-01 12:35 UTC, noobiba commented
I left single line comments. The username field is missing. The order of the fields might be reviewed. Name of placeholder is wrong.
@lauralindal @schultyy  Please review again. Thank you. :-)

2016-12-01 12:42 UTC, lauralindal commented
Sorry @noobiba this has already been merged. Will fix in another ticket. However, we don't need username *and* email - we will just use email :)