57 add legend for module status
lauralindal/dein-semesterplaner pull request #70
Opened 2016-12-11 20:48 UTC by noobiba

@lauralindal @sarahkami Please review for merge. Thank you! :)

2016-12-13 00:19 UTC, sarahkami approved these changes
I would move the static html from the react component to the html file. But if needed we can do it later on. So I approve ;)

2016-12-13 08:39 UTC, lauralindal requested changes

2016-12-13 08:39 UTC, lauralindal commented on src/ModulePlan.js
> +              <div><h6>Kurs belegt</h6></div>
"Kurs belegbar" or "Kurs verfügbar" would be better fitting, please adjust that :)

2016-12-13 08:39 UTC, lauralindal commented on src/ModulePlan.js
> +              <div><h6>Dringlichkeitskurs geplant</h6></div>
"Dringlicher Kurs geplant", maybe?

2016-12-13 08:39 UTC, lauralindal commented on src/ModulePlan.js
> +              <div><h6>Kurs beendet</h6></div>
"Kurs abgeschlossen" would be more accurate :)

2016-12-14 09:00 UTC, lauralindal approved these changes

2016-12-14 09:00 UTC, merged