Getting our data right
lauralindal/dein-semesterplaner pull request #85
Opened 2017-01-18 20:21 UTC by lauralindal

So, this is kind of a weird ticket. But it solves the question of when and where we want to get which data.
These are the steps 

1) Load seed Data for User from JSON file (this step is only needed for the prototype) on Sign Up and give it to hoodie
2) Load Hoodies data on Sign In and put it into state
3) If page is refreshed, get hoodie data and put it into state

I left some space for the originalUserData, which would be the module information dated to the end of the previous semester. However, this is probably better handled in #84 and will be combined.

2017-01-18 21:04 UTC, lauralindal commented
Dear @schultyy, would you have a look? :)

2017-01-18 21:35 UTC, schultyy requested changes
Requesting minor changes, apart from that looks good to me 🙆

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +        if (selectedModuleIds[i]===courseInfo[j].related_module_id)
I'd advise to not omit braces for if statements, for loops, etc.

The reason is the following:
It is easy to overread that the line after the if clause belongs to it, so it is easy to assume that the newly added line still belongs to the if case even though it doesn't.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +    var selectedModuleIds= [];
There's a space missing around the `=`.

```
var selectedModuleIds = [];
```

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +    var selectedModuleTitels= [];
Same as above.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +        if (selectedModuleIds[i]===modules[j].id)
Same case as with the if statement above.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +        userModules[i].selected= !userModules[i].selected;
There's a space missing left of the assignment. Same as above.

2017-01-18 21:35 UTC, schultyy commented on src/user.js
> +    return userModules;
`userModules` is undefined here. If you would like to return some data here, it should look like this: `return Promise.resolve(userModules);`.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
>      })
Semicolon is missing here.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
>    retrieveSelectedModuleTitel(){
Shouldn't this be `retrieveSelectedModuleTitle`?

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +      if (modules[i].id == courseInformation[j].related_module_id){
Here you should use three equal signs for comparison to prevent automatic type coercion.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +        if(userModules[i].status==="completed"){
Spaces are missing around `===`.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
>        if (userModules[i].module_id===moduleId){
Spaces are missing around `===`.

2017-01-18 21:35 UTC, schultyy commented on src/Home.js
> +    })
A semicolon is missing here.

2017-01-19 14:39 UTC, lauralindal commented on src/user.js
> +    return userModules;
I believe in this case, it's not undefined... We're creating the Variable userModules already before, so it should exist independently from the Promise?

2017-01-19 14:46 UTC, schultyy commented on src/user.js
> +    return userModules;
Yes, you're right I didn't read carefully here. My mistake.

2017-01-19 14:47 UTC, schultyy approved these changes

2017-01-19 14:55 UTC, lauralindal commented on src/user.js
> +    return userModules;
No problem :) (But yayyyyy for me being right for once :D)

2017-01-19 14:59 UTC, merged